line-api
Yukaii/zuzugo pull request #1
Opened 2023-02-05 17:34 UTC by steward379

2023-02-05 17:49 UTC, Yukaii requested changes

2023-02-05 17:49 UTC, Yukaii commented on pages/api/lineTest.ts
> +  sendLineNotify(`💩`, process.env.LINE_API_TOKEN);
可把 lineAPIToken 放到 `config.ts` 去

2023-02-05 17:49 UTC, Yukaii commented on pages/api/lineTest.ts
> +  sendLineNotify(`💩`, process.env.LINE_API_TOKEN);
message 可參考 slack 範例的值

https://github.com/Yukaii/zuzugo/blob/c491bbfc5cafe64443c5191f30e191eb49e46f23/lib/notification/slack.tsx#L22-L44

2023-02-05 17:49 UTC, Yukaii commented on tests/testLine.spec.ts
> +test("Send Line Notify", async () => {
Line 的測試先不會在 CI 上面跑，這邊先改成：


```suggestion
test.skip("Send Line Notify", async () => {
```

2023-02-06 10:00 UTC, steward379 commented on pages/api/lineTest.ts
> +  sendLineNotify(`💩`, process.env.LINE_API_TOKEN);
> 可把 lineAPIToken 放到 `config.ts` 去
已完成
> message 可參考 slack 範例的值
先以最基本的純文字作開展

2023-02-06 10:01 UTC, steward379 commented on tests/testLine.spec.ts
> +test("Send Line Notify", async () => {
> Line 的測試先不會在 CI 上面跑，這邊先改成：

done

2023-02-06 15:30 UTC, Yukaii commented on tests/testLine.spec.ts
> +test.skip("Send Line Notify", async () => {
在 main branch 我有新增 houseFactory 可以產生房屋資訊的假資料，可以拿來測試

https://github.com/Yukaii/zuzugo/blob/ba45a692661d46e5ba24f0afb643aeb7c8b5d24d/tests/factory.ts#L5-L6

2023-02-06 15:30 UTC, Yukaii commented on tests/testLine.spec.ts
> +test.skip("Send Line Notify", async () => {
記得 rebase 到 main

2023-02-07 08:45 UTC, steward379 commented on tests/testLine.spec.ts
> +test.skip("Send Line Notify", async () => {
already rebased

2023-02-07 10:39 UTC, Yukaii commented on tests/testLine.spec.ts
> +test.skip("Send Line Notify", async () => {
@steward379  那用假資料來送通知試試看？截張圖看看通知的結果如何~~

2023-02-08 05:53 UTC, Yukaii commented
因為 591 API 回傳的資料有變動，slack 訊息組合有改，Line 這邊也需要跟著修改

https://github.com/Yukaii/zuzugo/commit/f496e191183a1f3a5e1c06fdf740f0b5d506de5e

2023-02-08 05:54 UTC, Yukaii requested changes
修改 Line 訊息組成

2023-02-08 09:28 UTC, steward379 commented on tests/testLine.spec.ts
> +test.skip("Send Line Notify", async () => {
![Uploading 截圖 2023-02-08 17.27.53.png…]()

2023-02-08 09:28 UTC, steward379 commented on tests/testLine.spec.ts
> +test.skip("Send Line Notify", async () => {
<img width="1125" alt="截圖 2023-02-08 17 27 53" src="https://user-images.githubusercontent.com/10606663/217489778-6f2378d9-0dff-4f96-8c3e-e3f2d392ce7c.png">

2023-02-08 12:00 UTC, Yukaii commented
@steward379 測試沒過，也先幫我改成 `test.skip` 好了

2023-02-08 12:00 UTC, Yukaii commented on tests/testLine.spec.ts
> +test.skip("Send Line Notify", async () => {
Nice!

2023-02-08 12:01 UTC, Yukaii requested changes

2023-02-08 12:01 UTC, Yukaii commented on lib/notification/line.ts
> +  const blocks = HouseMessages({ houses: newHouses.reverse() }) as unknown as any[];
這邊前面幫我多加一個檢查

```ts
if (!config.tokenLine) {
  return
}
```

2023-02-08 12:07 UTC, Yukaii requested changes

2023-02-08 12:07 UTC, Yukaii commented on lib/notification/line.ts
> +/** @jsxImportSource jsx-line */
這邊可拿掉

```suggestion
```

2023-02-08 12:07 UTC, Yukaii commented on lineTest.ts
> +import type { NextApiRequest, NextApiResponse } from "next";
lineTest 這支檔案可以移除

2023-02-08 12:07 UTC, Yukaii commented on lib/__tests__/testLine.spec.ts
> +  在手機 App 打開 (${randomHouse.mobileUrl})
```suggestion
  在手機 App 打開 (${mobileUrl})
```

2023-02-08 12:07 UTC, Yukaii commented on tests/factory.ts
> +    mobileURL: faker.internet.url(),
這行不需要

```suggestion
```

2023-02-08 12:07 UTC, Yukaii commented on lib/notification/line.ts
> +      ${houses.map((house) => `${house} key=${house.post_id}`)}
```suggestion
${houses.map((house) => `${house} key=${house.post_id}`)}
```

2023-02-08 12:07 UTC, Yukaii commented on lib/notification/line.ts
> +  `;
```suggestion
`;
```

2023-02-08 12:07 UTC, Yukaii commented on lib/notification/line.ts
> +    `;
`; 可以移到前一行行尾

2023-02-08 12:11 UTC, Yukaii requested changes

2023-02-08 12:11 UTC, Yukaii commented on lib/__tests__/testLine.spec.ts
> +  🏠 ${randomHouse.title || ""}
前面的空白應該都可以清理下（包含這段字串其他部分）

```suggestion
🏠 ${randomHouse.title || ""}
```

2023-02-08 12:29 UTC, steward379 commented on lib/__tests__/testLine.spec.ts
> +  在手機 App 打開 (${randomHouse.mobileUrl})
會跳出 mobileUrl is not defined~

2023-02-08 12:36 UTC, Yukaii requested changes

2023-02-08 12:36 UTC, Yukaii commented on lib/notification/line.ts
> +}
這邊要呼叫 `sendLineNotify` 噢，然後要確定格式是正確的

2023-02-08 12:41 UTC, steward379 commented on lib/__tests__/testLine.spec.ts
> +  在手機 App 打開 (${randomHouse.mobileUrl})
因為在測試裡頭並沒有直接定義該靜態網址（可在此文件增加）

2023-02-08 13:18 UTC, steward379 commented on lib/notification/line.ts
> +}
await blocks

2023-02-12 13:30 UTC, moojing commented on lib/__tests__/testLine.spec.ts
> +  在手機 App 打開 (${randomHouse.mobileUrl})
@Yukaii 你是這個意思嗎？https://github.com/Yukaii/zuzugo/pull/1/commits/7991ae2402ed74eb69ce2f6a7f8973fd979f3076
然後我發現 house factory 裡面的類別 `DataItem` 跟這個 factory function  裡面資料的格式好像對不太起來，
例如 `cases_name` 在 factory 有，但在 DataItem 裡面沒有這個型別。

2023-02-12 13:30 UTC, moojing commented on tests/factory.ts
> +    mobileURL: faker.internet.url(),
removed [here](https://github.com/Yukaii/zuzugo/pull/1/commits/5f1e6f83976c5fca1654586ba5debb1ed375dd5e)

2023-02-12 13:32 UTC, moojing commented on lib/__tests__/testLine.spec.ts
> +  🏠 ${randomHouse.title || ""}
整理了一下格式，不過看起來好像不支援 markdown 
https://github.com/Yukaii/zuzugo/commit/7991ae2402ed74eb69ce2f6a7f8973fd979f3076
<img width="684" alt="Screenshot 2023-02-12 at 9 31 53 PM" src="https://user-images.githubusercontent.com/11360957/218314057-c8bf9f2f-42b3-4779-b0d1-24b2192787ac.png">

2023-02-12 15:54 UTC, Yukaii commented on lib/notification/line.ts
> +}
cc @moojing 這邊應該要改成

blocks.forEach(b => sendLineNotify(b)

之類的

2023-02-13 10:04 UTC, steward379 commented on lib/__tests__/testLine.spec.ts
> +  🏠 ${randomHouse.title || ""}
的確是不支援，我這陣子測試的東西比較偏向 Line API 的其他方式，至少圖文可以分開送出（貼圖也可以，但無關緊要）。
在測試中有通過了，另外 hashtag 是可以顯示的，可以參考我們的測試 line 群。
Line API Document (messaging API)
目前我只選用 Text msg 與 Image msg
https://developers.line.biz/en/docs/messaging-api/message-types/#text-messages

2023-02-13 10:05 UTC, steward379 commented on lib/__tests__/testLine.spec.ts
> +  🏠 ${randomHouse.title || ""}
[
<img width="714" alt="截圖 2023-02-13 18 04 55" src="https://user-images.githubusercontent.com/10606663/218428867-756fab8e-2709-4b04-8f7e-1e08f15ff92d.png">
](url)

2023-02-13 10:20 UTC, Yukaii commented on lib/__tests__/testLine.spec.ts
> +  在手機 App 打開 (${randomHouse.mobileUrl})
Sorry factory 是舊的 typing，要以 DataItem 為準

2023-02-13 13:52 UTC, Yukaii commented
/trunk merge

2023-02-13 14:07 UTC, merged