Line Text Format Cleanup
Yukaii/zuzugo pull request #80
Opened 2023-02-27 12:59 UTC by steward379

- if there's no tags, there won't be unnecessary empty ``;

2023-02-27 13:12 UTC, Yukaii requested changes

2023-02-27 13:12 UTC, Yukaii commented on lib/notification/line.ts
> +  house.rent_tag ? (rentTag = `\`${house.rent_tag?.map((tag) => tag.name)}\``) : (rentTag = ``);
```suggestion
  const rentTag =  house.rent_tag ? `\`${house.rent_tag?.map((tag) => tag.name)}\``) : '';
```

2023-02-27 14:06 UTC, moojing approved these changes

2023-02-27 15:40 UTC, moojing commented
branch murderer 🤯

2023-03-02 13:04 UTC, Yukaii approved these changes
<ruby>LGTM<rt>Looks Good To Me</rt></ruby>

2023-03-02 13:04 UTC, Yukaii commented
/trunk merge

2023-03-02 13:06 UTC, merged