[Feat] Add line bot webhook.
Yukaii/zuzugo pull request #89
Opened 2023-02-28 07:20 UTC by moojing

Add a web hook for the line bot, and pass testing data for now.

2023-03-01 03:31 UTC, Yukaii requested changes
也要解下衝突；

Line app 那邊可以開兩個，一個 local 一個 production

2023-03-01 03:31 UTC, Yukaii commented on lib/notification/lineBot.ts
> +  client.pushMessage(groupId, message)
要 await 或 return promise

2023-03-01 03:31 UTC, Yukaii commented on pages/api/line/events.ts
> +    sendLineBotMessage(chatId)
要 await

2023-03-04 07:58 UTC, moojing commented on pages/api/line/events.ts
> +    sendLineBotMessage(chatId)
done https://github.com/Yukaii/zuzugo/pull/89/commits/f5aab95b16ccc45549bd0e295a70913fe57804b3

2023-03-04 07:58 UTC, moojing commented on lib/notification/lineBot.ts
> +  client.pushMessage(groupId, message)
https://github.com/Yukaii/zuzugo/pull/89/commits/f5aab95b16ccc45549bd0e295a70913fe57804b3

2023-03-04 10:33 UTC, Yukaii requested changes

2023-03-04 10:33 UTC, Yukaii commented on lib/notification/lineBot.ts
> +  channelAccessToken: process.env.LINE_ACCESS_TOKEN || '',
env 也進 config.ts 吧~~可以弄成 scoped 的：

```ts
line: {
  accessToken: process.env.xxxxxx
}
```

2023-03-04 10:33 UTC, Yukaii commented on pages/api/line/events.ts
> +    await sendLineBotMessage(chatId)
這邊要 try catch 個？

2023-03-04 13:20 UTC, Yukaii requested changes

2023-03-04 13:20 UTC, Yukaii commented on lib/notification/lineBot.ts
> +    .then(() => {
噢發現你這邊就 catch 了，還是讓 error 浮到上層好了，這邊的 then 和 catch 就拿掉

2023-03-04 13:40 UTC, moojing commented on lib/notification/lineBot.ts
> +    .then(() => {
對椰

2023-03-04 19:02 UTC, Yukaii approved these changes
### **ドーンだYO!!**

![img](https://i.imgur.com/FxlAli4.jpg)

2023-03-04 19:02 UTC, Yukaii commented
/trunk merge

2023-03-04 19:04 UTC, merged